version: "3.8"

services:
  db_api_financas:
    image: postgres:17
    container_name: postgres_api_financas
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db_api_financas:/var/lib/postgresql/data
volumes:
  db_api_financas:
    driver: local
